config/routes.rb
Rails.application.routes.draw do

  devise_for :reviewers
  get 'welcome/index'

  resources :student_applications
  resources :student
  resources :welcome
  resources :reviewer

  devise_for :students

  root to: "welcome#index"
  get '/check_application_existence' => 'student_applications#check_application_existence', :as => 'mcheck_application_existence'
  get '/no_application' => 'welcome#no_application', :as => 'no_application_exists'
  get '/redirecting_show' => 'welcome#redirecting_show', :as => 'redirecting_for_show'
  get '/show_map' => 'welcome#show_map', :as => 'show_map'
  post '/admitted' => 'student_applications#admitted', :as => 'admitted'
  post '/rejected' => 'student_applications#rejected', :as => 'rejected'
  get '/about' => 'welcome#about', :as => 'about'
  get '/contact' => 'welcome#contact', :as => 'contact'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  include WelcomeHelper
  def index
  end

  def no_application
    if StudentApplication.exists?(:student_id => current_student.id)
      @no_appln = false
    else
      @no_appln = true
    end
  end
  helper_method :no_application

  def redirecting_show
    redirect_to :controller => "student_applications", :action => "show", :id => current_student.id

  end
  helper_method :redirecting_show

end

app/helpers/welcome_helper.rb
module WelcomeHelper
	def show_map
		@student_applications = StudentApplication.all
	end
	
	def about
	end

	def contact
	end
	
	def decision_made
		@student_application = StudentApplication.find_by student_id: current_student.id

		@app_status = AppStatus.find_by student_application_id: @student_application
		if @app_status.status != nil 
			@decision_made = true
		else
			@decision_made = false
		end
	end

	def decision
		@student_application = StudentApplication.find_by student_id: current_student.id

		@app_status = AppStatus.find_by student_application_id: @student_application
		if @app_status.status == 1 
			@decision = true
		else
			@decision = false
		end
	end
end

app/views/welcome/about.html.erb
<div class = "page-header"><h2>About</h2></div>

<div class="panel panel-primary">
	<div class = "panel-body">

	<p><h5>With more than 5,000 courses in 109 academic departments, University offers 125 majors to help you define your academic path. And 70 percent of our undergraduate classes have 30 or fewer students, maximizing your personal engagement with our internationally renowned faculty.Our faculty includes Nobel Prize winners, Fulbright Scholars and a Fields Medal recipient. Classes are stimulating. Coursework is challenging.</h5>

		<h5>Our academic requirements are among the most rigorous in the nation. But once our students arrive, they have the full force of our resources behind them. There are countless opportunities for research, fellowships and internships and for connecting with major players in almost any field. Whether you want to change a life, a generation or the whole world, imagine what you can do with the resources only UCLA can provide.</h5>

		<h5>University's graduate programs have a reputation for producing professionals, researchers and leaders who have a major impact on the world. With 40 programs ranked among the best in the nation, University gives today's graduate students the resources and cutting-edge instruction they need to go out and leave their own indelible mark. And with the second largest city in the U.S. in our backyard, learning extends beyond the classroom. Engaging with the community, while being part of an academic system that is well connected and respected throughout the world, creates an educational experience that cannot be replicated anywhere else.</h5></p>
		<br />

	</div>
</div>

app/views/welcome/contact.html.erb
<div class = "page-header"><h2>Contact Information</h2></div>

<div class="panel panel-primary">
	<div class = "panel-body">

		<h4>General Contact Information</h4>
		<p>Telephone (Campus Operator): 310-825-4321</p>
		<br />

		<h4>Address</h4>

		<p>Please use the Campus Directory to find the complete mailing address for individuals or departments. Note that a street address is not required by the Post Office, as the entire Los Angeles 90095 zip code is assigned to the campus.</p>

		<p>To find delivery addresses for campus buildings, see page 2 of the University Campus map (PDF).</p>

		<br />

	</div>
</div>

app/views/welcome/index.html.erb
<% if notice!= nil %>
<div class="alert alert-info" role="alert"><%= notice %></div>
<% end %>
<div class="panel panel-primary">
  <div class = "panel-body">
    <h2>Welcome to the University of California, Los Angeles</h2>
    <!--<h1>Welcome to the University , Apply by clciking on Apply Here</h1>-->

    <% if student_signed_in? %>
    <% if no_application %>
    <!--  If student is logged in and have not created an application -->
    <%= link_to 'New Application', new_student_application_path, class:"btn btn-primary"%>
    <%= link_to 'View Statistics', show_map_path, class:"btn btn-primary", 'data-no-turbolink' => true %>
    <% else %>

    <% if decision_made %>
    <% if decision %>
    <div class="alert alert-info" role="alert"> Decision is now available, please check your email.</div>
    <% else %>
    <div class="alert alert-info" role="alert">Decision is now available, please check your email.</div>
    <% end %>
    <% end %>
    <!--  If student is logged in and already has an application -->
    <%= link_to 'Retrieve Application', redirecting_for_show_path(@student_application), class:"btn btn-primary"%></li>
    <%= link_to 'View Statistics', show_map_path, class:"btn btn-primary", 'data-no-turbolink' => true %>
    <!--<li><%= link_to 'Sign Out', destroy_student_session_path, :method => :delete %></li>-->
    <% end %>
    <% elsif reviewer_signed_in? %>
    <%= link_to 'Applications ', student_applications_path, :method => :get, :action => :index, class:"btn btn-primary" %>
    <%= link_to 'Admitted Applications', admitted_path, :method => :post, class:"btn btn-success" %>
    <%= link_to 'Rejected Applications', rejected_path, :method => :post, class:"btn btn-danger" %>
    <!--<%= link_to 'Reviewer Sign Out', destroy_reviewer_session_path, :method => :delete, class: "btn btn-primary" %>-->
    <% else %>

    <%= link_to 'Apply Here', new_student_registration_path, class:"btn btn-primary" %>
    <%= link_to 'Continue With Your Application', new_student_session_path, class:"btn btn-primary" %>
    <%= link_to 'Review Applications', new_reviewer_session_path, class:"btn btn-primary" %>
    <%= link_to 'View Statistics', show_map_path, class:"btn btn-primary", 'data-no-turbolink' => true %>

    <% end %>
    <br />
    <br />

    <h5>With more than 5,000 courses in 109 academic departments, UCLA offers 125 majors to help you define your academic path. And 70 percent of our undergraduate classes have 30 or fewer students, maximizing your personal engagement with our internationally renowned faculty.Our faculty includes Nobel Prize winners, Fulbright Scholars and a Fields Medal recipient. Classes are stimulating. Coursework is challenging.</h5>

    <h5>Our academic requirements are among the most rigorous in the nation. But once our students arrive, they have the full force of our resources behind them. There are countless opportunities for research, fellowships and internships and for connecting with major players in almost any field. Whether you want to change a life, a generation or the whole world, imagine what you can do with the resources only UCLA can provide.</h5>

    <h5>UCLA's graduate programs have a reputation for producing professionals, researchers and leaders who have a major impact on the world. With 40 programs ranked among the best in the nation, UCLA gives today's graduate students the resources and cutting-edge instruction they need to go out and leave their own indelible mark. And with the second largest city in the U.S. in our backyard, learning extends beyond the classroom. Engaging with the community, while being part of an academic system that is well connected and respected throughout the world, creates an educational experience that cannot be replicated anywhere else.</h5>
    <br />

  </div>
</div>

app/views/welcome/show_map.html.erb
<div class = "page-header"><center><h2>View Statistics</h2></center></div>

<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
<style type="text/css">
  html { height: 100%; }
  body { height: 100%; margin: 0px; padding: 0px;  }
</style>
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>

<!-- Creating an array of the the names and lat long -->

<script type="text/javascript">
    //document.write("H1");
    //document.write("<br />");
    var array_loc = [];
    //document.write(array_loc);
    //var i=0;
  </script>

  <% @student_applications.each do |student_application| %>

  <script type="text/javascript">
    //document.write(i);
  //  document.write("In script");
    //document.write('<%= student_application.address %>');
    array_loc.push(['<%= student_application.city %>',<%= student_application.latitude %>,<%= student_application.longitude %>]);
    //array_loc[i] = "Shraddha";
    //  document.write(array_loc);
    i=i+1;
  </script>
 <% end %>

  <script type="text/javascript"
  src="http://maps.google.com/maps/api/js?sensor=false">
</script>
<body>
  <div id="map_canvas" style="width:55%; height:60%; margin: 0 auto 0 auto"></div>
  <center><b><i> *****Markers show the locations of all the applicants***** </i></b></center>
  <br /><br />
  <div class="panel panel-primary">
    <div class = "panel-body">

  <script type="text/javascript">
    //document.write("Hello");


    //  document.write(array_loc);
    var map = new google.maps.Map(document.getElementById('map_canvas'), {
      zoom: 1,
      minZoom: 1,
      center: new google.maps.LatLng(30,-20),
      mapTypeId: google.maps.MapTypeId.ROADMAP
    });

    var infowindow = new google.maps.InfoWindow();

    var marker, j;

    for (j = 0; j < array_loc.length; j++) {
      marker = new google.maps.Marker({
        position: new google.maps.LatLng(array_loc[j][1], array_loc[j][2]),
        size: new google.maps.Size(100, 100),
        map: map
      });


      google.maps.event.addListener(marker, 'click', (function(marker, j) {
        return function() {
          infowindow.setContent(array_loc[j][0]);
          infowindow.open(map, marker);
        }
      })(marker, j));
    }

  </script>

  <hr />

  <b> Total Number of Applicants : </b>&nbsp;&nbsp;&nbsp;<%= StudentApplication.count %>
  <%
  count_admitted = 0
  count_rejected = 0
  @app_status = AppStatus.all
  @app_status.each do |app_status|
   %>
   <%
   if app_status.status == true
    count_admitted = count_admitted + 1
  elsif app_status.status == false
    count_rejected = count_rejected + 1
  end
end
%>
<hr />
<b> Number of Admitted Students : </b>&nbsp;&nbsp;&nbsp;<%= count_admitted %>
<hr />
<b> Number of Rejected Students : </b>&nbsp;&nbsp;&nbsp;<%= count_rejected %>

<hr />
<div class = "piecharts" style = "text-align:center">
<b> Percentage of Applicants based on GPA </b>
<%= pie_chart StudentApplication.group(:gpa).count %>
<hr />
<b> Percentage of Applicants based on Address </b>
<%= pie_chart StudentApplication.group(:state).count %>
<hr />
<hr />
</div>
</div></div>