config/routes.rb
Rails.application.routes.draw do

  devise_for :reviewers
  get 'welcome/index'

  resources :student_applications
  resources :student
  resources :welcome
  resources :reviewer

  devise_for :students

  root to: "welcome#index"
  get '/check_application_existence' => 'student_applications#check_application_existence', :as => 'mcheck_application_existence'
  get '/no_application' => 'welcome#no_application', :as => 'no_application_exists'
  get '/redirecting_show' => 'welcome#redirecting_show', :as => 'redirecting_for_show'
  get '/show_map' => 'welcome#show_map', :as => 'show_map'
  post '/admitted' => 'student_applications#admitted', :as => 'admitted'
  post '/rejected' => 'student_applications#rejected', :as => 'rejected'
  get '/about' => 'welcome#about', :as => 'about'
  get '/contact' => 'welcome#contact', :as => 'contact'

end

app/models/student_application.rb
class StudentApplication < ActiveRecord::Base
  belongs_to :Student
  has_one :app_status, :dependent => :destroy
  geocoded_by :city
  after_validation :geocode, :if => :city_changed?

  # all fields must be filled
  validates :name, :phone, :email_id, :gpa, :address, :city, :state, :country, :dob, presence: true
  validates :resume, :sop, :lor, attachment_size: { less_than: 5.megabytes }

  # Phone should be a number and its length should be between 10 and 15 characters
  validates :phone,  :numericality => true,
                     :length => { :minimum => 10, :maximum => 15 }

  # Validate email using the regex provided by Devise
  validates_format_of :email_id,:with => Devise::email_regexp, :uniqueness => true

# check if GPA lies in the correct range
  validates :gpa, :numericality => { less_than_or_equal_to:4.0, greater_than_or_equal_to: 2.5 }

  #validates :dob, date: { before: Date.today }

# Validate Address

# File Uploads

has_attached_file :resume
validates_attachment_content_type :resume, :content_type => %w(application/pdf)

has_attached_file :sop
validates_attachment_content_type :sop, :content_type => %w(application/pdf)

has_attached_file :lor
validates_attachment_content_type :lor, :content_type => %w(application/pdf)

def self.all_cached
  Rails.cache.fetch('StudentApplication.all') { all }
end

end

app/controllers/student_applications_controller.rb
class StudentApplicationsController < ApplicationController
  include StudentApplicationsHelper
  before_action :set_student_application, only: [:show, :edit, :update, :destroy]
  # Removing the next line because if not removed it always redirects to the student login page in case of reviewer too
  #before_action :authenticate_student!
  # GET /student_applications
  # GET /student_applications.json
  def index
    @student_applications = StudentApplication.all.paginate(page: params[:page], per_page: 5).order('id ASC')
  end

  # GET /student_applications/1
  # GET /student_applications/1.json
  def show
  end

  # GET /student_applications/new
  def new
    #@student_application = StudentApplication.new
    #@profile = current_user.build_profile(params[:id])
    if student_signed_in?
      @student_application = current_student.build_student_application
    end
  end

  # GET /student_applications/1/edit
  def edit
  end

  def delete
  end

  # POST /student_applications
  # POST /student_applications.json
  def create
    #@student_application = StudentApplication.new(student_application_params)
    #@new_student = Student.find(params[:id])
    @student_application = current_student.create_student_application(student_application_params)

    respond_to do |format|
      if @student_application.save
        format.html { redirect_to @student_application, notice: 'Student application was successfully created.' }
        format.json { render :show, status: :created, location: @student_application }
        AppStatus.create(student_application_id: @student_application.id, student_name: @student_application.name)
      else
        format.html { render :new }
        format.json { render json: @student_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /student_applications/1
  # PATCH/PUT /student_applications/1.json
  def update
    respond_to do |format|
      if @student_application.update(student_application_params)
        format.html { redirect_to @student_application, notice: 'Student application was successfully updated.' }
        format.json { render :show, status: :ok, location: @student_application }
        #AppStatus.create(student_application_id: "@student_application.id")
      else
        format.html { render :edit }
        format.json { render json: @student_application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /student_applications/1
  # DELETE /student_applications/1.json
  def destroy
    #if :delete_app_status
      @student_application.destroy
      respond_to do |format|
        format.html { redirect_to welcome_index_path, notice: 'Student application was successfully destroyed.' }
        format.json { head :no_content }
      end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student_application
      if student_signed_in?
        if StudentApplication.exists?(:student_id => current_student.id)
          @student_application = StudentApplication.find_by student_id: current_student.id
        else
          @student_application = StudentApplication.find(params[:id])
        end
      else
        @student_application = StudentApplication.find(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_application_params
      #params.require(:student_application).permit(:student_id, :name, :phone, :email_id, :gpa, :address, :resume_file_name, :sop_file_name, :lor_file_name)
      params.require(:student_application).permit(:student_id, :name, :phone, :email_id, :gpa, :address, :resume, :sop, :lor, :city, :state, :country, :dob)
    end

    # check if an application already exists for current_student
    def check_application_existence
      if StudentApplication.exists?(:student_id => current_student.id)
        @no_appln = false
      else
        @no_appln = true
      end
    end
    helper_method :check_application_existence

  end

app/helpers/student_applications_helper.rb
module StudentApplicationsHelper
	
	def cache_key_for_studentapplication_table
		"student_application-table-#{StudentApplication.maximum(:updated_at)}"
	end

	def cache_key_for_studentapplication_row(student_application)
		"student_application-#{student_application.id}-#{student_application.updated_at}"
	end

	def admitted
		@student_applications = StudentApplication.all

		@app_id = params[:student_application_id]
		@reviewer_id = params[:reviewer_id]

		AppStatus.where(student_application_id: @app_id).limit(1).update_all(status: 1, reviewer_id: @reviewer_id)
	end

	def rejected
		@student_applications = StudentApplication.all

		@app_id = params[:student_application_id]
		@reviewer_id = params[:reviewer_id]

		AppStatus.where(student_application_id: @app_id).limit(1).update_all(status: 0, reviewer_id: @reviewer_id)
	end

	
end

app/views/student_applications/_form.html.erb
<%= form_for(@student_application, :html => { :multipart => true }) do |f| %>
<% if @student_application.errors.any? %>
<div id="error_explanation">
  <h3><%= pluralize(@student_application.errors.count, "error") %> prohibited this student_application from being saved:</h3>

  <ul>
    <% @student_application.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="alert alert-warning" role="alert">
  <ul>
    <li><i>Resume, SOP and LOR need to be PDF files</i></li>
    <li><i>GPA needs to be between 3.0 - 4.0</i></li>
  </ul>
</div>


<div class="panel panel-primary">
  <div class = "panel-body">
    <table class = "table">

      <tr>
        <div class="field">
          <td><strong><%= f.label :name %></strong></td>
          <td><%= f.text_field :name %></td>
        </div>
      </tr>

      <tr>
        <div class="field">
          <td><strong><%= f.label "Date of Birth" %></strong></td>
          <td><%= f.date_select :dob, :start_year => 1950 %></td>
        </div>
      </tr>

      <tr>
        <div class="field">
          <td><strong><%= f.label :phone %></strong></td>
          <td><%= f.text_field :phone %></td>
        </div>
      </tr>

      <tr>
        <div class="field">
          <td><strong><%= f.label "Email ID" %></strong></td>
          <td><%= f.text_field :email_id %></td>
        </div>
      </tr>

      <tr>
        <div class="field">
          <td><strong><%= f.label :gpa %></strong></td>
          <td><%= f.text_field :gpa %></td>
        </div>
      </tr>

      <tr>
        <div class="field">
          <td><strong><%= f.label "Street Address" %></strong></td>
          <td><%= f.text_field :address %></td>
        </div>
      </tr>


      <tr>
        <div class="field">
          <td><strong><%= f.label :city %></strong></td>
          <td><%= f.text_field :city %></td>
        </div>
      </tr>


      <tr>
        <div class="field">
          <td><strong><%= f.label :state %></strong></td>
          <td><%= f.text_field :state %><i>(Two letter initials : eg. CA)</i></td>
        </div>
      </tr>


      <tr>
        <div class="field">
          <td><strong><%= f.label :country %></strong></td>
          <td><%= f.text_field :country %></td>
        </div>
      </tr>

      <tr>
        <div class="field">
          <td><strong><%= f.label :resume %></strong></td>
          <td><%= f.file_field :resume %></td>
        </div>
      </tr>

      <tr>
        <div class="field">
          <td><strong><%= f.label "Statement Of Purpose" %></strong></td>
          <td><%= f.file_field :sop %></td>
        </div>
      </tr>

      <tr>
        <div class="field">
          <td><strong><%= f.label "Letter Of Recommendation" %></strong></td>
          <td><%= f.file_field :lor %></td>
        </div>
      </tr>
    </table>
  </div>

</div>

<center><div class="actions">
  <%= f.submit "Submit", class: "btn btn-primary" %>
</div></center>
<% end %>

app/views/student_applications/admitted.html.erb
 <p id="notice"><%= notice %></p>
 <% if reviewer_signed_in? %>
 <div class = "page-header"><h3>Admitted Student Applications</h3></div>

 <% @app_status = AppStatus.all %>


 <table class = "table">
  <thead>
    <tr>
      <th>Application Id</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @app_status.each do |app_status| %>
    <% if app_status.status == true %>
    <tr>
      <td><%= app_status.student_application_id %></td>
      <td><%= app_status.student_name %></td>
    </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/student_applications/edit.html.erb
<div class = "page-header"><h3>Editing Student Application</h3></div>

<% if student_signed_in? %>
<%= render 'form' %> 
<br>
<center>
	<%= link_to 'Show', @student_application, class:"btn btn-primary" %> 
	<%= link_to 'Back', welcome_index_path, class:"btn btn-primary" %> 
</center>
<% end %>

app/views/student_applications/index.html.erb
 <p id="notice"><%= notice %></p>
 <% if reviewer_signed_in? %>
 <div class = "page-header"><h3>Listing Student Applications</h3></div>

 <table class = "table">
  <thead>
    <tr>
      <th>Application Id</th>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Gpa</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @app_status = AppStatus.all
    @app_status.each do |app_status|

      if app_status.reviewer_id == nil %>

      <% @student_applications.each do |student_application| %>
      <% if app_status.student_application_id == student_application.id %>
      <tr>

        <td><%= student_application.id %></td>
        <td><%= student_application.name %></td>
        <td><%= student_application.phone %></td>
        <td><%= student_application.email_id %></td>
        <td><%= student_application.gpa %></td>
        <td>
          <%= student_application.address %><br />
          <%= student_application.city %><br />
          <%= student_application.state %><br />

        </td>
        <td><%= link_to 'Show', student_application %></td>

      </tr>
      <% end %>
      <% end %>
      <% end %>
      <% end %>
    </tbody>
    <center><div><%= will_paginate @student_applications %></div></center>
  </table>
  <% end %>

app/views/student_applications/new.html.erb
<div class = "page-header"><h3>New Student Application</h3></div>
<% if student_signed_in? %>
<%= render 'form' %>

<center><%= link_to 'Back', welcome_index_path, class:"btn btn-primary" %></center>

<% end %>

app/views/student_applications/rejected.html.erb
<p id="notice"><%= notice %></p>
<% if reviewer_signed_in? %>
<div class = "page-header"><h3>Rejected Student Applications</h3></div>

<% @app_status = AppStatus.all %>


<table class = "table">
  <thead>
    <tr>
      <th>Application Id</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @app_status.each do |app_status| %>
      <% if app_status.status == false && app_status.reviewer_id != nil %>
      <tr>
        <td><%= app_status.student_application_id %></td>
        <td><%= app_status.student_name %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/student_applications/show.html.erb
<div class = "page-header"><h3>Student Application</h3></div>
<div class="panel panel-primary">
  <!--<div class="panel-title"><strong>Student Application<strong></div>-->
  <div class = "panel-body">
    <table class = "table">
      <% if student_signed_in? || reviewer_signed_in? %>
      <tr>
        <td><strong>Name:</strong></td>
        <td><%= @student_application.name %></td>
      </tr>

      <tr>
        <td><strong>Date of Birth:</strong></td>
        <td><%= @student_application.dob %></td>
      </tr>

      <tr>
        <td><strong>Phone:</strong></td>
        <td><%= @student_application.phone %></td>
      </tr>

      <tr>
        <td><strong>Email:</strong></td>
        <td><%= @student_application.email_id %></td>
      </tr>

      <tr>
        <td><strong>GPA:</strong></td>
        <td><%= (@student_application.gpa).round(2) %></td>
      </tr>

      <tr>
        <td><strong>Address:</strong></td>
        <td><%= @student_application.address %><br />
        <%= @student_application.city %>,
        <%= @student_application.state %>,
        <%= @student_application.country %></td>
      </tr>

      <tr>
        <td><strong>Resume:</strong></td>
        <td><%= link_to 'Resume', @student_application.resume.url, target:"_blank" %></td>
      </tr>

      <tr>
        <td><strong>Statement Of Purpose:</strong></td>
        <td><%= link_to 'SOP', @student_application.sop.url, target:"_blank" %></td>
      </tr>

      <tr>
        <td><strong>Letter Of Recommendation:</strong></td>
        <td><%= link_to 'LOR', @student_application.lor.url, target:"_blank" %></td>
      </tr>
    </table>
  </div>
</div>

<% end %>

<% if student_signed_in? %>
<% if decision_made %>
<center><%= link_to 'Back', welcome_index_path, class:"btn btn-primary" %></center>
<% else %>
<center>
  <%= link_to 'Edit', edit_student_application_path(@student_application), class:"btn btn-primary" %>
  <%= link_to 'Back', welcome_index_path, class:"btn btn-primary" %>
  <%= link_to 'Destroy', @student_application, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-primary" %>
</center>
<% end %>

<% elsif reviewer_signed_in? %>
<center>
  <%= button_to 'Admit', {:controller => "student_applications", :action => "admitted", :student_application_id => @student_application.id, :reviewer_id => current_reviewer.id} , :method=>:post, :class => "btn btn-success"  %>
  <%= button_to 'Reject', {:controller => "student_applications", :action => "rejected", :student_application_id => @student_application.id, :reviewer_id => current_reviewer.id} , :method=>:post, :class => "btn btn-danger"  %>
  <%= link_to 'Back', welcome_index_path, class:"btn btn-primary" %>
</center>
<% end %>