config/routes.rb
Rails.application.routes.draw do

  devise_for :reviewers
  get 'welcome/index'

  resources :student_applications
  resources :student
  resources :welcome
  resources :reviewer

  devise_for :students

  root to: "welcome#index"
  get '/check_application_existence' => 'student_applications#check_application_existence', :as => 'mcheck_application_existence'
  get '/no_application' => 'welcome#no_application', :as => 'no_application_exists'
  get '/redirecting_show' => 'welcome#redirecting_show', :as => 'redirecting_for_show'
  get '/show_map' => 'welcome#show_map', :as => 'show_map'
  post '/admitted' => 'student_applications#admitted', :as => 'admitted'
  post '/rejected' => 'student_applications#rejected', :as => 'rejected'
  get '/about' => 'welcome#about', :as => 'about'
  get '/contact' => 'welcome#contact', :as => 'contact'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>AppTracker</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true, :cache => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true, :cache => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<header class="navbar navbar-inverse" role="navigation">
		<div class = "navbar-inner">
			<div class="container">
				<div id = "logo" class = "navbar-brand"><%= link_to 'UNIVERSITY HOME', root_path %></div>

				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<% if student_signed_in? %>
					<ul class="nav navbar-nav navbar-right">
						<li class="active"><%= link_to 'Student Sign Out', destroy_student_session_path, :method => :delete%></li>
					</ul>

					<%elsif reviewer_signed_in? %>

					<ul class="nav navbar-nav navbar-right">
						<li class="active"><%= link_to 'Reviewer Sign Out', destroy_reviewer_session_path, :method => :delete%></li>
					</ul>


					<% else %>

					<ul class="nav navbar-nav pull-right">
						<li class="active"><%= link_to 'Sign Up', new_student_registration_path %></li>
						<li class="active"><%= link_to 'Sign In', new_student_session_path %></li>
					</ul>
					<% end %>
				</div>
			</div>
		</div>
	</header>

	<div class ="panel-footer">
		<nav>
			<small>
				<%= link_to "About",   about_path %>
				<%= link_to "Contact", contact_path %>
			</small>
		</nav>
	</div>
	<!--<h6> **** UNIVERSITY HOME **** </h6>-->
	<%= yield %>

</body>
</html>